/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prensece.form;

/**
 *
 * @author atang
 */
public class MainApp extends javax.swing.JFrame {

    /**
     * Creates new form MainApp
     */
    public MainApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        transaksiMenu = new javax.swing.JMenu();
        absensiStaffMenuItem = new javax.swing.JMenuItem();
        absensiSiswaMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        masterMenu = new javax.swing.JMenu();
        jabatanMenuItem = new javax.swing.JMenuItem();
        staffMenuItem = new javax.swing.JMenuItem();
        siswaMenuItem = new javax.swing.JMenuItem();
        kelasMenuItem = new javax.swing.JMenuItem();
        penggunaMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        transaksiMenu.setMnemonic('f');
        transaksiMenu.setText("Absensi");

        absensiStaffMenuItem.setMnemonic('o');
        absensiStaffMenuItem.setText("Staff");
        transaksiMenu.add(absensiStaffMenuItem);

        absensiSiswaMenuItem.setMnemonic('s');
        absensiSiswaMenuItem.setText("Siswa");
        transaksiMenu.add(absensiSiswaMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        transaksiMenu.add(exitMenuItem);

        menuBar.add(transaksiMenu);

        masterMenu.setMnemonic('e');
        masterMenu.setText("Master");

        jabatanMenuItem.setMnemonic('t');
        jabatanMenuItem.setText("Jabatan");
        jabatanMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabatanMenuItemActionPerformed(evt);
            }
        });
        masterMenu.add(jabatanMenuItem);

        staffMenuItem.setMnemonic('y');
        staffMenuItem.setText("Staff");
        staffMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffMenuItemActionPerformed(evt);
            }
        });
        masterMenu.add(staffMenuItem);

        siswaMenuItem.setMnemonic('p');
        siswaMenuItem.setText("Siswa");
        siswaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siswaMenuItemActionPerformed(evt);
            }
        });
        masterMenu.add(siswaMenuItem);

        kelasMenuItem.setMnemonic('d');
        kelasMenuItem.setText("Kelas");
        kelasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasMenuItemActionPerformed(evt);
            }
        });
        masterMenu.add(kelasMenuItem);

        penggunaMenuItem.setText("Pengguna");
        penggunaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penggunaMenuItemActionPerformed(evt);
            }
        });
        masterMenu.add(penggunaMenuItem);

        menuBar.add(masterMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void jabatanMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabatanMenuItemActionPerformed
        JabatanForm jbForm = new JabatanForm();
        jbForm.setVisible(true);
        desktopPane.add(jbForm);
    }//GEN-LAST:event_jabatanMenuItemActionPerformed

    private void staffMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffMenuItemActionPerformed
        StaffForm staffForm = new StaffForm();
        staffForm.setVisible(true);
        desktopPane.add(staffForm);
    }//GEN-LAST:event_staffMenuItemActionPerformed

    private void kelasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasMenuItemActionPerformed
        KelasForm kelasForm = new KelasForm();
        kelasForm.setVisible(true);
        desktopPane.add(kelasForm);
    }//GEN-LAST:event_kelasMenuItemActionPerformed

    private void siswaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siswaMenuItemActionPerformed
        SiswaForm siswaForm = new SiswaForm();
        siswaForm.setVisible(true);
        desktopPane.add(siswaForm);
    }//GEN-LAST:event_siswaMenuItemActionPerformed

    private void penggunaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penggunaMenuItemActionPerformed
        PenggunaForm penggunaForm = new PenggunaForm();
        penggunaForm.setVisible(true);
        desktopPane.add(penggunaForm);
    }//GEN-LAST:event_penggunaMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem absensiSiswaMenuItem;
    private javax.swing.JMenuItem absensiStaffMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem jabatanMenuItem;
    private javax.swing.JMenuItem kelasMenuItem;
    private javax.swing.JMenu masterMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem penggunaMenuItem;
    private javax.swing.JMenuItem siswaMenuItem;
    private javax.swing.JMenuItem staffMenuItem;
    private javax.swing.JMenu transaksiMenu;
    // End of variables declaration//GEN-END:variables

}
